language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W+SAPG1ocVbvZju8JMpo6BB94lwZc3IU6TE11qT6q+2otG54v80JFhpQ+SGyhS8ht1JXgXyMDZwhdZ+WcFa+e9Ff2UXhLgd4AO29/VfTalZS9fOi8WkYnkcvkVB46El1vb/woIKrg2dGTqJGl9YJ4DsXGdSAYggmqytaElmEN4dAFIXYLGpqsf164qqwP+AshL+cd0O1xIzVy1uKRes/9QcZBtagDG3XsDs6xIcCBLz/x2l5F/8HkrSYD5BXidpQma+XbCznOhkEck/sVYhRIJo6P4WOHysY1F64wTGVtPyu2L1nRCNuOKeS2cm1LCtrVOB3bxHmiZEnC7RcjLn0kmifqcfgspDb2pP/Xyjf2LdymPv4K/0/NTqYZlap170gcUghTqc+hrNdjB4g2H3OEuDScAtLITqKKvlGB4KI/A9F2bXGtUiUiAyYCHv92rJUo4JcM+Nr2KKSQor/32YUgezOeFn0pa1Yq9+1FCIDQlJki4Hfz2ynlN5Qib1bFiCSRh35Z5d+OBpbecsSbJ0yrw5/BsbJmFP1t+EW0NdPP/cjvbBq2KjT2k27DfIxUCpnpvrPoUobFA/Zk/mq/EOtQ5qYf+GlEwgis81Rq9qIXWSvrEI/bqEkx2tUoCwQav06J1Z2atXPKMRwb/dH5xun7+wcv2NpY6knqafe8eTMFO0=
exclude:
- vendor
sudo: false
