language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W+04JQvTTQzavy5Y8A3L1+SCWDdkeg7jTgZ48Ta/p+hWsoFj1i9euJ3Cp7pksGCQ6Jgzm0jGhq5ntdWp7pHZd1ES7KAMoHLhh3KTovUGBZTcU7F4JqDgEsdwL26vczKqxvKxWtF5P6zWlsKc8oew2MzQCRjOHeeyucvsYyRhI86MBcf9nOB3kHYzXgOtu2xDGIgoO+Ru0MSRzMnMIQxo6C9DGeCBgWnp+bvZjNHiECgkjfrFk1lK6XJjUDYzdBdo+IOujoUUlf45jk4f0KxfWNxcue4e2OMgFLOi5tghRu66cUWqYRvBUqLI3H6xWqPRJury0YuL1xHpDmL6/tdzwjIManvOTZgSCSEgd0Kfx6Y4zoWa84vysjZiXkSE3jNAPb2dpxDhAnRI9SbFSDIDlvt43P0ZrYxI/jRSO8N/lvrvqxTqIKdMgX50sYDU4fVCHVdJVCLNDwupzacjleLUA6v5spsLPLETjbIahWQ1+iI4cnG4cOLbFHHG815tx7Yn3T5L1QWa6pW095v03QwiEvAB72QfMnEB+HBiYqoCE+NtTTpX4nHpK2WcbSXS4z1EnbtD+AFRliW8v80BJP8TVFJmIqCNYtRPkXpB8KgzhsiBEGFRUZtIlKsLSzcfXjUBzSS8+C+zGZjwlrPe15IOb2SOHb9WIaKfyZEx/JJQtrY=
  - secure: hJssgzSZo4VKfInmFV/JwJ8OMZHkyW1ASnrjr6bnIXk4AM+QU10GtQXZsENRqyfiH/AAo0fCR77O7xx0AnKp91AgknoRc9ulJFCgC8xaSDFurzMixG69XZ4jD6WB2jLjCoxlWwUYSWi00QNp3X+5GrFnZ+FaIBfEJPF8+6Uo5021qyvgOccboUrTbXy3don2zH2V5X78L+myqr1hy/ak9HZBc+1Hw9FBfcuNdQDM+WXPiHDfyOk3vuybzZ8OJVNd8CPuYZZrKR6gYFNO/ww/O9qVpK5tZki6e9TV0fLc3IdMaDRARtQdR6f+75HxxfArKs98FRN/UQT4HuONeCMCBgkKtj0jpTYQJTbKC1lnhPoIiAiRbdp8DW5+AdBczSCj0kJbKcesSK3HKrFVKkCfEToDtyxXhNuomPiOrR8IoG0RFm90MDHE2XvWjU1d0UcnOqXAUbuOZkyoyZOcY2dFdeKrbxd966lEzXQEHH7NakhHdI8izK5Aoo1yXzrTgtVAgnBWPbQwYIYG4ogK7K1sZvayILtCzzPSIpxMMpyTa/SfSBV7GWmlSrdo17mzuTGS4rjIXLxyzLLorjKqy508I1El3E1EM8mYeURI+mv9B8E52q1D1I6lUZgAKcRju9J5aDh4Fr3mMZ8gAdFa5fgQjeH+GrFLB+96e2wbowYcrN4=
exclude:
- vendor
sudo: false
