language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W+04JQvTTQzavy5Y8A3L1+SCWDdkeg7jTgZ48Ta/p+hWsoFj1i9euJ3Cp7pksGCQ6Jgzm0jGhq5ntdWp7pHZd1ES7KAMoHLhh3KTovUGBZTcU7F4JqDgEsdwL26vczKqxvKxWtF5P6zWlsKc8oew2MzQCRjOHeeyucvsYyRhI86MBcf9nOB3kHYzXgOtu2xDGIgoO+Ru0MSRzMnMIQxo6C9DGeCBgWnp+bvZjNHiECgkjfrFk1lK6XJjUDYzdBdo+IOujoUUlf45jk4f0KxfWNxcue4e2OMgFLOi5tghRu66cUWqYRvBUqLI3H6xWqPRJury0YuL1xHpDmL6/tdzwjIManvOTZgSCSEgd0Kfx6Y4zoWa84vysjZiXkSE3jNAPb2dpxDhAnRI9SbFSDIDlvt43P0ZrYxI/jRSO8N/lvrvqxTqIKdMgX50sYDU4fVCHVdJVCLNDwupzacjleLUA6v5spsLPLETjbIahWQ1+iI4cnG4cOLbFHHG815tx7Yn3T5L1QWa6pW095v03QwiEvAB72QfMnEB+HBiYqoCE+NtTTpX4nHpK2WcbSXS4z1EnbtD+AFRliW8v80BJP8TVFJmIqCNYtRPkXpB8KgzhsiBEGFRUZtIlKsLSzcfXjUBzSS8+C+zGZjwlrPe15IOb2SOHb9WIaKfyZEx/JJQtrY=
exclude:
- vendor
sudo: false
