# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# accessed via {{ site.title }}, {{ site.email }}

title: 재윤 블로그
description: >- # this means to ignore newlines until "baseurl:"
  개발/디자인에 관심 많은 대학생이 공부한 것, 생각한 것, 경험한 것들을 기록하고 정리하는 공간입니다.
url: "http://blog.jaeyoon.io" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name:   JaeYoon Song
  url:    http://jaeyoon.io
  email:  song@jaeyoon.io
lang: ko_KR
email: song@jaeyoon.io

twitter_username: song_jaeyoon
github_username:  jyoonsong

color-scheme: black

# Set encoding to UTF-8
encoding: utf-8

# Date format
jyoon:
  date_format: "%Y.%m.%d"
  
# Collections for Category
collections:
  category:
    output: true

# Build settings
markdown: kramdown
theme: jekyll-jyoon
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-feed
  - jekyll-seo-tag
    
# Add a default layout
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
